notifications:
  recipients:
    - sagittarius-ci@googlegroups.com
language: c
sudo: required
os:
  - linux
  - osx

branches:
  only:
    - master

before_install:
  - rm -rf $HOME/.sagittarius
  - echo `pwd`
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo chown -R $(whoami) /usr/local; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew upgrade; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install bdw-gc; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libffi; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install openssl; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install cmake libgc-dev zlib1g-dev libffi-dev; fi
  - curl -L -o version https://bitbucket.org/ktakashi/sagittarius-scheme/downloads/latest-version.txt
  - curl -L -o sagittarius.tar.gz https://bitbucket.org/ktakashi/sagittarius-scheme/downloads/sagittarius-`cat version`.tar.gz
  - tar xvf sagittarius.tar.gz
  - cd sagittarius-`cat version`
  - if [ `cat ../version` = "0.6.7" ]; then curl -L -o osx.patch https://bitbucket.org/ktakashi/sagittarius-scheme/downloads/sagittarius-0.6.7-osx.patch; fi
  - if [ `cat ../version` = "0.6.7" ]; then patch -p1 < osx.patch; fi
  - if [ `cat ../version` = "0.9.0" ]; then curl -L -o osx.patch https://bitbucket.org/ktakashi/sagittarius-scheme/downloads/sagittarius-0.9.0-osx.patch; fi
  - if [ `cat ../version` = "0.9.0" ]; then patch -p1 < osx.patch; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cmake . -DFFI_LIBRARY_DIR=/usr/local/Cellar/libffi/3.0.13/lib; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cmake .; fi
  - make
  - sudo make install
  - cd $TRAVIS_BUILD_DIR
  - echo `pwd`
  - rm -rf $HOME/.sagittarius

before_script:
  - ./dist.sh gen
  - cmake .

script:
  - make
  - make test
