pipelines:
  default:
    - step:
        script:
          - echo "Installing required packages"
          - apt-get update
          - apt-get install cmake libgc-dev zlib1g-dev libffi-dev -y
          - echo "Retrieving the latest version of Sagittarius"
          - curl -o latest-version.txt https://bitbucket.org/ktakashi/sagittarius-scheme/downloads/latest-version.txt
          - curl -o sagittarius.tar.gz https://bitbucket.org/ktakashi/sagittarius-scheme/downloads/sagittarius-`latest-version.txt`.tar.gz
          - tar -xvf sagittarius.tar.gz
          - cd sagittarius-`latest-version.txt`
          - cmake .
          - make -j8 install
          - cd ..
          - ./dist.sh gen
          - cmake .
          - make -j8
          - make test