version: 2
jobs:
   build:
     docker:
       - image: buildpack-deps:bionic
         environment:
           ENV: CI
     steps:
       - run:
           name: Checkout repository
           command: |
             apt-get update
             apt-get -y install mercurial
             hg clone https://bitbucket.org/ktakashi/sagittarius-scheme sagittarius-scheme
       - run:
           name: Installing dependencies
           command: apt-get -y install cmake libgc-dev zlib1g-dev libffi-dev
       - run:
           name: Installing current Sagittarius
           working_directory: ~/current_sagittarius
           command: |
             curl -L -o version https://bitbucket.org/ktakashi/sagittarius-scheme/downloads/latest-version.txt
             curl -L -o sagittarius.tar.gz https://bitbucket.org/ktakashi/sagittarius-scheme/downloads/sagittarius-`cat version`.tar.gz
             tar --no-same-owner -xvf sagittarius.tar.gz
             cd sagittarius-`cat version`
             cmake .
             make -j8 sash
             make
             make install
       - run:
           name: Pre-build
           working_directory: ~/project/sagittarius-scheme
           command: |
             pwd
             ./dist.sh gen
             cmake .
       - run:
           name: Build
           working_directory: ~/project/sagittarius-scheme
           command: make
       - run:
           name: Test
           working_directory: ~/project/sagittarius-scheme
           command: make test
       - run:
           name: JSON related tests
           working_directory: ~/project/sagittarius-scheme
           command: make test-jsons
