version: 2
jobs:
   build:
     machine: true
     steps:
       - run:
           name: Checkout repository
           command: |
             sudo apt-get update
             sudo apt-get upgrade
             sudo apt-get install mercurial
             hg clone https://bitbucket.org/ktakashi/sagittarius-scheme sagittarius-scheme
             pwd
             ls
       - run:
           name: Installing dependencies
           command: sudo apt-get install cmake libgc-dev zlib1g-dev libffi-dev
       - run:
           name: Installing current Sagittarius
           working_directory: ~/current_sagittarius
           command: |
             curl -L -o version https://bitbucket.org/ktakashi/sagittarius-scheme/downloads/latest-version.txt
             curl -L -o sagittarius.tar.gz https://bitbucket.org/ktakashi/sagittarius-scheme/downloads/sagittarius-`cat version`.tar.gz
             tar xvf sagittarius.tar.gz
             cd sagittarius-`cat version`
             cmake .
             make -j8 sash
             make
             sudo make install
       - run:
           name: Pre-build
           working_directory: ~/project/sagittarius-scheme
           command: |
             pwd
             ./dist.sh gen
             cmake .
       - run:
           name: Build
           working_directory: ~/project/sagittarius-scheme
           command: make
       - run:
           name: Test
           working_directory: ~/project/sagittarius-scheme
           command: make test
       - run:
           name: JSON related tests
           working_directory: ~/project/sagittarius-scheme
           command: make test-jsons
