version: 2
jobs:
   build:
     docker:
       - image: circleci/postgres:9.6
     steps:
       - checkout
       - run:
           name: Installing dependencies
           command: sudo apt-get install cmake libgc-dev zlib1g-dev libffi-dev
       - run:
           name: Installing current Sagittarius
           working_directory: ~/current_sagittarius
           command: |
             curl -L -o version https://bitbucket.org/ktakashi/sagittarius-scheme/downloads/latest-version.txt
             curl -L -o sagittarius.tar.gz https://bitbucket.org/ktakashi/sagittarius-scheme/downloads/sagittarius-`cat version`.tar.gz
             tar xvf sagittarius.tar.gz
             cd sagittarius-`cat version`
             cmake .
             make -j8 sash
             make
             sudo make install
       - run:
           name: Pre-build
           command: |
             ./dist.sh gen
             cmake .
       - run:
           name: Build
           command: make
       - run:
           name: Test
           command: make test
