version: 2
jobs:
   build:
     docker:
       - image: buildpack-deps:bionic
         environment:
           ENV: CI
     steps:
       - checkout:
           path: ~/project/sagittarius-scheme
       - run:
           name: Installing dependencies
           command: |
             bash .ci/setup-ubuntu.sh
       - run:
           name: Installing current Sagittarius
           working_directory: ~/current_sagittarius
           command: |
             bash ./ci/build-current.sh 'no'
       - run:
           name: Pre-build
           working_directory: ~/project/sagittarius-scheme
           command: |
             ./dist.sh gen
             cmake .
       - run:
           name: Build
           working_directory: ~/project/sagittarius-scheme
           command: make
       - run:
           name: Test
           working_directory: ~/project/sagittarius-scheme
           command: make test
       - run:
           name: JSON related tests
           working_directory: ~/project/sagittarius-scheme
           command: make test-jsons
