version: 2
jobs:
   build:
     docker:
       - image: buildpack-deps:bionic
         environment:
           ENV: CI
     steps:
       - checkout:
           path: ~/target
       - run:
           name: Installing dependencies
           working_directory: ~/
           command: |
             bash target/.ci/setup-ubuntu.sh
       - run:
           name: Installing current Sagittarius
           working_directory: ~/current_sagittarius
           command: |
             bash ../target/.ci/build-current.sh 'no'
       - run:
           name: Pre-build
           working_directory: ~/target
           command: |
             ./dist.sh gen
             cmake .
       - run:
           name: Build
           working_directory: ~/target
           command: make
       - run:
           name: Test
           working_directory: ~/target
           command: make test
       - run:
           name: JSON related tests
           working_directory: ~/target
           command: make test-jsons
