name: Nightly Docker container build

# Once a day
on:
  schedule:
    - cron: '30 2 * * *'

jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v3
      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"
        
  scan:
    runs-on: ubuntu-latest
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    steps:
      - uses: actions/checkout@v3
      - name: DockerHub Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Metadata action
        uses: docker/metadata-action@v4.1.1
        id: meta
        with:
          images: ktakashi/sagittarius
          tags: |
            type=schedule,pattern=nightly
          flavor: latest=false
          labels: |
            org.opencontainers.image.authors=Takashi Kato
            org.opencontainers.image.version=nightly
            org.opencontainers.image.title=Sagittarius Scheme nightly build container
      - name: Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          file: .ci/Dockerfile.nightly
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            COMMIT=${{ github.sha }}
